apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: arbiter
  annotations:
    github.com/project-slug: khulnasoft/arbiter
    github.com/team-slug: khulnasoft/link
spec:
  type: external-tooling
  lifecycle: "-"
  owner: link
