version: 2.1

orbs:
  prodsec: khulnasoft/prodsec-orb@1.0

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - khulnasoft-bot-slack
          channel: team-link-pipeline-info
          filters:
            branches:
              ignore:
                - main
